/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Classes.CasaResidencialBuilder_EduardoGiovanniLuan;
import Classes.CasaResidencial_EduardoGiovanniLuan;
import static Classes.Contadores_EduardoGiovanniLuan.getCodigoImovel;
import Classes.Imobiliaria_EduardoGiovanniLuan;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Portu
 */
public class CadastroCasa extends javax.swing.JDialog {

    /**
     * Creates new form CadastroCasa
     */
    public CadastroCasa(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

        buttonEnviar.setEnabled(false);
        addTextFieldListeners();
        verificarCampos();

        comboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonResetar = new javax.swing.JButton();
        buttonEnviar = new javax.swing.JButton();
        inputRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        inputDataConstrucao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputAreaTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputAreaConstruida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputQtdDormitorios = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inputQtdBanheiros = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inputQtdVagas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        inputIPTU = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        inputVenda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        inputAluguel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        comboModelo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(220, 10, 45));

        jLabel1.setBackground(new java.awt.Color(40, 170, 253));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 170, 253));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE CASA RESIDENCIAL");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));

        buttonResetar.setText("RESETAR");
        buttonResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetarActionPerformed(evt);
            }
        });

        buttonEnviar.setText("ENVIAR");
        buttonEnviar.setEnabled(false);
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        inputRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRuaActionPerformed(evt);
            }
        });

        jLabel6.setText("Rua:");

        inputNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumeroActionPerformed(evt);
            }
        });

        jLabel7.setText("Número:");

        inputBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBairroActionPerformed(evt);
            }
        });

        jLabel8.setText("Bairro:");

        inputCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCidadeActionPerformed(evt);
            }
        });

        jLabel12.setText("Cidade:");

        inputDataConstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataConstrucaoActionPerformed(evt);
            }
        });

        jLabel9.setText("Data de Construcao:");

        inputAreaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAreaTotalActionPerformed(evt);
            }
        });

        jLabel10.setText("Area total:");

        inputAreaConstruida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAreaConstruidaActionPerformed(evt);
            }
        });

        jLabel11.setText("Area Construida:");

        inputQtdDormitorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQtdDormitoriosActionPerformed(evt);
            }
        });

        jLabel13.setText("Quantidade de dormitórios:");

        inputQtdBanheiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQtdBanheirosActionPerformed(evt);
            }
        });

        jLabel14.setText("Quantidade de banheiros:");

        inputQtdVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQtdVagasActionPerformed(evt);
            }
        });

        jLabel15.setText("Quantidade de vagas:");

        inputIPTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIPTUActionPerformed(evt);
            }
        });

        jLabel16.setText("Valor do IPTU:");

        inputVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVendaActionPerformed(evt);
            }
        });

        jLabel17.setText("Valor de Venda:");

        inputAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAluguelActionPerformed(evt);
            }
        });

        jLabel18.setText("Valor de aluguél:");

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Simples", "Luxo", "Padrão" }));
        comboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputDataConstrucao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputRua, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBairro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputAreaConstruida, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputQtdDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inputIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputQtdBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputQtdVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(inputCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(inputDataConstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(inputAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(5, 5, 5)
                        .addComponent(inputAreaConstruida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(5, 5, 5)
                            .addComponent(inputQtdDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(5, 5, 5)
                            .addComponent(inputQtdBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(inputQtdVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(5, 5, 5)
                        .addComponent(inputIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(27, 27, 27))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetarActionPerformed
        inputRua.setText("");
        inputNumero.setText("");
        inputBairro.setText("");
        inputCidade.setText("");
        inputDataConstrucao.setText("");
        inputAreaTotal.setText("");
        inputAreaConstruida.setText("");
        inputQtdDormitorios.setText("");
        inputQtdBanheiros.setText("");
        inputQtdVagas.setText("");
        inputIPTU.setText("");
        inputVenda.setText("");
        inputAluguel.setText("");

        buttonEnviar.setEnabled(false);
    }//GEN-LAST:event_buttonResetarActionPerformed

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        CasaResidencialBuilder_EduardoGiovanniLuan builder = new CasaResidencialBuilder_EduardoGiovanniLuan();

        int codigoImovel = getCodigoImovel();
        String rua = inputRua.getText();
        String numero = inputNumero.getText();
        String bairro = inputBairro.getText();
        String cidade = inputCidade.getText();
        String endereco = rua + ", numero " + numero + ", " + bairro + ", " + cidade;
        LocalDate dataConstrucao;
        try {
            String texto = inputDataConstrucao.getText();
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            dataConstrucao = LocalDate.parse(texto, formato);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Formato de data inválido! Use o formato dd/MM/yyyy.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        float areaTotal = Float.parseFloat(inputAreaTotal.getText());
        float areaConstruida = Float.parseFloat(inputAreaConstruida.getText());
        int qtdDormitorios = Integer.parseInt(inputQtdDormitorios.getText());
        int qtdBanheiros = Integer.parseInt(inputQtdBanheiros.getText());
        int qtdVagas = Integer.parseInt(inputQtdVagas.getText());
        float IPTU = Float.parseFloat(inputIPTU.getText());
        float venda = Float.parseFloat(inputVenda.getText());
        float aluguel = Float.parseFloat(inputAluguel.getText());

        CasaResidencial_EduardoGiovanniLuan novaCasa = builder
                .codigo(codigoImovel)
                .endereco(endereco)
                .dataConstrucao(dataConstrucao)
                .areaTotal(areaTotal)
                .construida(areaConstruida)
                .dormitorios(qtdDormitorios)
                .banheiros(qtdBanheiros)
                .vagas(qtdVagas)
                .iptu(IPTU)
                .venda(venda)
                .aluguel(aluguel)
                .build();

        Imobiliaria_EduardoGiovanniLuan nossaImobiliaria = Imobiliaria_EduardoGiovanniLuan.getInstancia();
        nossaImobiliaria.getImoveis().add(novaCasa);
        JOptionPane.showMessageDialog(null,
                "CADASTRO EFETUADO COM SUCESSO!",
                "",
                JOptionPane.PLAIN_MESSAGE);

        dispose();
    }//GEN-LAST:event_buttonEnviarActionPerformed

    private void inputRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRuaActionPerformed

    private void inputNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumeroActionPerformed

    private void inputBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBairroActionPerformed

    private void inputCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCidadeActionPerformed

    private void inputDataConstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataConstrucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataConstrucaoActionPerformed

    private void inputAreaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAreaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAreaTotalActionPerformed

    private void inputAreaConstruidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAreaConstruidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAreaConstruidaActionPerformed

    private void inputQtdDormitoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQtdDormitoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQtdDormitoriosActionPerformed

    private void inputQtdBanheirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQtdBanheirosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQtdBanheirosActionPerformed

    private void inputQtdVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQtdVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputQtdVagasActionPerformed

    private void inputIPTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIPTUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIPTUActionPerformed

    private void inputVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVendaActionPerformed

    private void inputAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAluguelActionPerformed

    private void comboModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModeloActionPerformed
        String modeloSelecionado = (String) comboModelo.getSelectedItem();

        // builder temporário
        CasaResidencialBuilder_EduardoGiovanniLuan builder = new CasaResidencialBuilder_EduardoGiovanniLuan();

        // Aplica o modelo, o que define os valores internos do Builder
        if ("Simples".equals(modeloSelecionado)) {
            builder.modeloSimples();
        } else if ("Luxo".equals(modeloSelecionado)) {
            builder.modeloLuxo();
        } else if ("Padrão".equals(modeloSelecionado)){ // Padrão
            builder.modeloPadrao();
        }

        inputQtdDormitorios.setText(String.valueOf(builder.getQtdDormitorios()));
        inputQtdBanheiros.setText(String.valueOf(builder.getQtdBanheiros()));
        inputQtdVagas.setText(String.valueOf(builder.getQtdVagasGaragem()));
        inputAreaTotal.setText(String.valueOf(builder.getAreaTotal()));
        inputAreaConstruida.setText(String.valueOf(builder.getAreaConstruida()));
        inputIPTU.setText(String.valueOf(builder.getValorIPTU()));
        inputAluguel.setText(String.valueOf(builder.getValorAluguel()));
        inputVenda.setText(String.valueOf(builder.getValorVenda()));
        verificarCampos();
    }//GEN-LAST:event_comboModeloActionPerformed

    private void verificarCampos() {
        boolean todosPreenchidos
                = !inputRua.getText().trim().isEmpty()
                && !inputNumero.getText().trim().isEmpty()
                && !inputBairro.getText().trim().isEmpty()
                && !inputCidade.getText().trim().isEmpty()
                && !inputDataConstrucao.getText().trim().isEmpty()
                && !inputAreaTotal.getText().trim().isEmpty()
                && !inputAreaConstruida.getText().trim().isEmpty()
                && !inputQtdDormitorios.getText().trim().isEmpty()
                && !inputQtdBanheiros.getText().trim().isEmpty()
                && !inputQtdVagas.getText().trim().isEmpty()
                && !inputIPTU.getText().trim().isEmpty()
                && !inputVenda.getText().trim().isEmpty()
                && !inputAluguel.getText().trim().isEmpty();
        buttonEnviar.setEnabled(todosPreenchidos);
    }

    private void addTextFieldListeners() {
        DocumentListener listener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                verificarCampos();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                verificarCampos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                verificarCampos();
            }
        };

        inputRua.getDocument().addDocumentListener(listener);
        inputNumero.getDocument().addDocumentListener(listener);
        inputBairro.getDocument().addDocumentListener(listener);
        inputCidade.getDocument().addDocumentListener(listener);
        inputDataConstrucao.getDocument().addDocumentListener(listener);
        inputAreaTotal.getDocument().addDocumentListener(listener);
        inputAreaConstruida.getDocument().addDocumentListener(listener);
        inputQtdDormitorios.getDocument().addDocumentListener(listener);
        inputQtdBanheiros.getDocument().addDocumentListener(listener);
        inputQtdVagas.getDocument().addDocumentListener(listener);
        inputIPTU.getDocument().addDocumentListener(listener);
        inputVenda.getDocument().addDocumentListener(listener);
        inputAluguel.getDocument().addDocumentListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroCasa dialog = new CadastroCasa(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JButton buttonResetar;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JTextField inputAluguel;
    private javax.swing.JTextField inputAreaConstruida;
    private javax.swing.JTextField inputAreaTotal;
    private javax.swing.JTextField inputBairro;
    private javax.swing.JTextField inputCidade;
    private javax.swing.JTextField inputDataConstrucao;
    private javax.swing.JTextField inputIPTU;
    private javax.swing.JTextField inputNumero;
    private javax.swing.JTextField inputQtdBanheiros;
    private javax.swing.JTextField inputQtdDormitorios;
    private javax.swing.JTextField inputQtdVagas;
    private javax.swing.JTextField inputRua;
    private javax.swing.JTextField inputVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
